CREATE DATABASE hospital_DB;

USE hospital_DB;


-- DROP TABLE IF EXISTS patients;
CREATE TABLE IF NOT EXISTS PATIENTS
(
	ID VARCHAR(36) PRIMARY KEY,
	FIRST_NAME VARCHAR(200) NOT NULL,
	LAST_NAME VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ELECTRONIC_CABINET_ID VARCHAR(36),
    INSURANCE_NUMBER VARCHAR(36),
    WARD_ID INT
--     FOREIGN KEY (ELECTRONIC_CABINET_ID) REFERENCES ELECTRONIC_CABINET(ID),
--     FOREIGN KEY (WARD_ID) REFERENCES WARD(ID)
);

ALTER TABLE PATIENTS
COMMENT = "Table to store PATIENTS' information";

ALTER TABLE PATIENTS
MODIFY COLUMN ID VARCHAR(36) COMMENT 'Unique identifier for each PATIENT',
MODIFY COLUMN FIRST_NAME VARCHAR(200) NOT NULL COMMENT 'First name of the PATIENT',
MODIFY COLUMN LAST_NAME VARCHAR(200) NOT NULL COMMENT 'Last name of the PATIENT',
MODIFY COLUMN EMAIL VARCHAR(200) NOT NULL COMMENT 'Email address of the PATIENT',
MODIFY COLUMN PHONE VARCHAR(20) NOT NULL COMMENT 'Phone number of the PATIENT',
MODIFY COLUMN ELECTRONIC_CABINET_ID VARCHAR(36) COMMENT 'THE NUMBER OF ELECTRONIC CABINET OF A PATIENT',
MODIFY COLUMN INSURANCE_NUMBER VARCHAR(36) COMMENT 'INSURANCE NUMBER OF A PATIENT',
MODIFY COLUMN WARD_ID INT COMMENT 'WARD OF THE PATIENT'


select * from patients;

-- побачити коменти
SELECT column_name, column_comment
FROM information_schema.columns
WHERE table_name = 'PATIENTS';