CREATE DATABASE hospital_DB;

USE hospital_DB;

----------------------------------------------------------- PATIENTS table ------------------------------

-- DROP TABLE IF EXISTS patients;
CREATE TABLE IF NOT EXISTS PATIENTS
(
	ID VARCHAR(36) PRIMARY KEY,
	FIRST_NAME VARCHAR(200) NOT NULL,
	LAST_NAME VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ELECTRONIC_CABINET_ID VARCHAR(36),
    INSURANCE_NUMBER VARCHAR(36),
    WARD_ID INT
--     FOREIGN KEY (ELECTRONIC_CABINET_ID) REFERENCES ELECTRONIC_CABINET(ID),
--     FOREIGN KEY (WARD_ID) REFERENCES WARD(ID)
);

ALTER TABLE PATIENTS
COMMENT = "Table to store PATIENTS' information";

ALTER TABLE PATIENTS
MODIFY COLUMN ID VARCHAR(36) COMMENT 'Unique identifier for each PATIENT',
MODIFY COLUMN FIRST_NAME VARCHAR(200) NOT NULL COMMENT 'First name of the PATIENT',
MODIFY COLUMN LAST_NAME VARCHAR(200) NOT NULL COMMENT 'Last name of the PATIENT',
MODIFY COLUMN EMAIL VARCHAR(200) NOT NULL COMMENT 'Email address of the PATIENT',
MODIFY COLUMN PHONE VARCHAR(20) NOT NULL COMMENT 'Phone number of the PATIENT',
MODIFY COLUMN ELECTRONIC_CABINET_ID VARCHAR(36) COMMENT 'THE NUMBER OF ELECTRONIC CABINET OF A PATIENT',
MODIFY COLUMN INSURANCE_NUMBER VARCHAR(36) COMMENT 'INSURANCE NUMBER OF A PATIENT',
MODIFY COLUMN WARD_ID INT COMMENT 'WARD OF THE PATIENT'


select * from patients;

-- побачити коменти
SELECT column_name, column_comment
FROM information_schema.columns
WHERE table_name = 'PATIENTS';

----------------------------------------------------------- PATIENTS table ------------------------------

----------------------------------------------------------- DOCTORS table ------------------------------

-- DROP TABLE IF EXISTS DOCTORS;
CREATE TABLE IF NOT EXISTS DOCTORS
(
	ID VARCHAR(36) PRIMARY KEY,
	FIRST_NAME VARCHAR(200) NOT NULL,
	LAST_NAME VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	DEPARTMENT_ID VARCHAR(36),
    ROOM_ID VARCHAR(36),
    SPECIALIZATION VARCHAR(200)
--     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
--     FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)
);

ALTER TABLE DOCTORS
COMMENT = "Table to store DOCTORS' information";

ALTER TABLE DOCTORS
MODIFY COLUMN ID VARCHAR(36) COMMENT 'Unique identifier for each DOCTOR',
MODIFY COLUMN FIRST_NAME VARCHAR(200) NOT NULL COMMENT 'First name of the DOCTORS',
MODIFY COLUMN LAST_NAME VARCHAR(200) NOT NULL COMMENT 'Last name of the DOCTORS',
MODIFY COLUMN EMAIL VARCHAR(200) NOT NULL COMMENT 'Email address of the DOCTORS',
MODIFY COLUMN PHONE VARCHAR(20) NOT NULL COMMENT 'Phone number of the DOCTORS',
MODIFY COLUMN DEPARTMENT_ID VARCHAR(36) COMMENT 'DOCTOR DEPARTMENT ID',
MODIFY COLUMN ROOM_ID VARCHAR(36) COMMENT 'DOCTOR ROOM ID',
MODIFY COLUMN SPECIALIZATION VARCHAR(200) COMMENT 'DOCTOR SPECIALIZATION'


select * from DOCTORS;

-- побачити коменти
SELECT column_name, column_comment
FROM information_schema.columns
WHERE table_name = 'DOCTORS';

----------------------------------------------------------- DOCTORS table ------------------------------